### PR TITLE
CMake: adopt CMAKE_INSTALL_LIBDIR for more locations

### PR DESCRIPTION
**Pull request by bramoosterhuis**
When playing around with a multilib environment, I noticed that if our libs are built 64bit, those libs end up in (/usr/lib) aka  /usr/lib32. This is caused because we hardcode all the install locations. Let us leverage the use of GNUInstallDirs to dynamically install binaries to the default install locations set by build systems and package generators.

This PR is part of a series of PR's
https://github.com/rdkcentral/Thunder/pull/1604
https://github.com/rdkcentral/ThunderTools/pull/93
https://github.com/rdkcentral/ThunderInterfaces/pull/347
https://github.com/rdkcentral/ThunderClientLibraries/pull/257
https://github.com/rdkcentral/ThunderUI/pull/99
https://github.com/WebPlatformForEmbedded/ThunderNanoServicesRDK/pull/301
https://github.com/WebPlatformForEmbedded/ThunderLibraries/pull/39

### CODE REVIEW

**Comment by VeithMetro** [comment]
@bramoosterhuis looks like the Windows build is failing for some reason, here is the error with more detail: https://github.com/rdkcentral/ThunderNanoServices/actions/runs/9141745017/job/25215219174?pr=789#step:16:1557

Also, a similar problem to the ones in different repos, which I guess could be because we need to merge Thunder first?
```
CMake Error at CECControl/cmake_install.cmake:60 (file):
  file cannot create directory: /wpeframework/plugins.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
FAILED: CMakeFiles/install.util 
```

**Comment by bramoosterhuis** [comment]
> @bramoosterhuis looks like the Windows build is failing for some reason, here is the error with more detail: https://github.com/rdkcentral/ThunderNanoServices/actions/runs/9141745017/job/25215219174?pr=789#step:16:1557
> 
> Also, a similar problem to the ones in different repos, which I guess could be because we need to merge Thunder first?
> 
> ```
> CMake Error at CECControl/cmake_install.cmake:60 (file):
>   file cannot create directory: /wpeframework/plugins.  Maybe need
>   administrative privileges.
> Call Stack (most recent call first):
>   cmake_install.cmake:47 (include)
> FAILED: CMakeFiles/install.util 
> ```

Yeah you are correct, thunder need to be merged first. Since it is merged now, I re-run the tests.

**Review by pwielders — APPROVED** [review]

**Comment by VeithMetro** [comment]
@bramoosterhuis @pwielders I don't think that the Windows build failing is anyhow connected to these changes, right?
```
8>JsonGenerator : error : : TestController.json: $ref file 'common.json' not found in any of the interface paths
8>JSONGenerator
8>JsonGenerator : error : : TestUtility.json: $ref file 'common.json' not found in any of the interface paths
8>JSONGenerator
```

**Comment by pwielders** [comment]
> @bramoosterhuis @pwielders I don't think that the Windows build failing is anyhow connected to these changes, right?
> 
> ```
> 8>JsonGenerator : error : : TestController.json: $ref file 'common.json' not found in any of the interface paths
> 8>JSONGenerator
> 8>JsonGenerator : error : : TestUtility.json: $ref file 'common.json' not found in any of the interface paths
> 8>JSONGenerator
> ```

Yes it was but it should be fixed by now :-)

**Comment by VeithMetro** [comment]
@pwielders seems to be fixed indeed, but there is another build issue, probably also not connected with changes from this PR
```
1>D:\a\ThunderNanoServices\ThunderNanoServices\ThunderOnWindows\ThunderNanoServices\examples\OutOfProcessPlugin\OutOfProcessImplementation.cpp(366,99): error C3861: 'Connector': identifier not found
```
Here in more detail: https://github.com/rdkcentral/ThunderNanoServices/actions/runs/9222328620/job/25373265173?pr=789#step:16:925

**Comment by pwielders** [comment]
@VeithMetro corect. That issue is fixed here: https://github.com/rdkcentral/ThunderNanoServices/pull/795 waiting for a review of @HaseenaSainul . Will merge that one first than this one should complete correctly as well..

**Pull request merged**
