### PR TITLE
[IOConnector] Support for single GPIO configuration and GPIO above 255

### PR DESCRIPTION
**Pull request by arun-madhavan-013**
… number in IO Connector Plugin

Reason for change: IO Connector plugin was not able to accept single GPIO configuration. IO Connector plugin was not able to export GPIO pin values which are greater than 255.
Test Procedure: Please see ticket for details.
Risks: None.

Signed-off-by: Arun P Madhavan <arun_madhavan@comcast.com>

### CODE REVIEW

**Comment by woutermeek** [comment]
@arun-madhavan-013 could you please sign the CLA?

**Comment by arun-madhavan-013** [comment]
> @arun-madhavan-013 could you please sign the CLA?

I've already signed the CLA but some how its still showing as "You have signed the CLA already but the status is still pending? Let us recheck it."
Could you please help me here ?

**Comment by arun-madhavan-013** [comment]
> > @arun-madhavan-013 could you please sign the CLA?
> 
> I've already signed the CLA but some how its still showing as "You have signed the CLA already but the status is still pending? Let us recheck it."
> Could you please help me here ?

Now its updated, Thanks.

**Comment by woutermeek** [comment]
@arun-madhavan-013 great, we will review the PR asap.

**Pull request merged**
