### PR TITLE
WebShell: config update

### PR DESCRIPTION
**Pull request by HaseenaSainul**

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Haseena: We had to change the copyright headers back to Metrological in this repo, and the tools are now set up for this.  Picking up the latest from master should fix it.
Thanks,
Martin Hughes RDK CMF Compliance Team

**Comment by HaseenaSainul** [comment]
Ok, thanks, will wait for the update

**Comment by HaseenaSainul** [comment]
HI @mhughesacn, I did not see any pull request available to relicense to 'Metrological' for this repo. Eventhough the copyright provided with the modified file is already under metrological. So can we proceed with this pull request ?

**Comment by mhughesacn** [comment]
Hi Haseena: Line 4 of one of the files needs to say "Copyright 2020 Metrological" instead of "RDK Management".  The Pull Req to relicense ThunderNanoServices is already merged as of yesterday (Tuesday).
For all these repos, the tool is now set up to look for Metrological copyrights in scans, so it will complain even in other branches.  I agree that this will cause some pain for a while until everything is Metrological.

**Comment by HaseenaSainul** [comment]
Thanks @mhughesacn, after update branch, the changes from master is reflected with this dev branch. So now it is ready to merge

**Review by pwielders — APPROVED** [review]

**Pull request merged**
