### PR TITLE
Introduce BluetoothAudioSink

### PR DESCRIPTION
**Pull request by sebaszm**
- Introduce BluetoothAudioSink plugin
- BluetoothControl: some fixes around BR/EDR connection, have baudrate configurable from build system (audio requires more than the hardcoded 115200)
- BluetoothRemoteControl: changes due to renamed Profile to GATTProfile

### CODE REVIEW

**Review by pwielders — APPROVED** [review]
Wow, that was a lot of work :-) Looks good!

**Comment by pwielders** [comment]
@mhughesacn can you have a look at this. It seems you need to approve if the changes are oke, so we can merge it.

**Review by mhughesacn — APPROVED** [review]

**Comment by mhughesacn** [comment]
Sorry guys, didn't realise that I was blocking anything when the checks were passing.

**Comment by pwielders** [comment]
@mhughesacn No problem. Thanks !

**Pull request merged**
